[package]
name = "self-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "selfstorage"
path = "src/lib.rs"

[[bin]]
name = "selfstorer"
path = "src/main.rs"

[dev-dependencies]
rand = "*"
